id: PA73445B0
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: de
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    1b597cf641724c44bc9c836bea1030ba:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    f174ca6d2a16413582e0a45752914936:
      title: The Benefits of Saving Lives
      parent: Advice
    29d1b58c32ab453987c154855d5a6c3d:
      title: Words of Advice
      parent: Advice
    96a960ddd7f348e499f14a64c5542bda:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    18ea1ba6394b47d69a4a0e2bd9d0faca:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    916ea8b420a844119d8b2d74776918e2:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    f369e00dd5a948448d84160afb442e21:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    859969584d8b4fd79f32bb52da481c6f:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    16c28de447b34169b48410defcee0baa:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    d72872545ed0456899367086faa64353:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    a61cffada74c4983a39dd35e0ad9854f:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    d4eb9105ece54a73b62cebe863d0e6bc:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    289e5b6c410c48a3bdf407186a0652c9:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    a03d1510011b42709c5595b39c648cd3:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.129467'
last_modified_at: '2022-02-28T22:42:38.129470'
